### ISSUE TITLE
Not clear that Mapzen's hoverboard library is different from the original

### ISSUE THREAD

**Issue by rmglennon** [mapzen/hoverboard#6]
A user (Aaron W) at the Mapzen SF open house on Sept 1, 2015 mentioned some problems with Hoverboard. 

He had used the standard Hoverboard library and it wasn't working with Mapzen's tiles. Suggested that Mapzen makes it clear on the website (https://mapzen.com/projects/vector-tiles) and in this repository that there are some differences. In other words, if you want to use Hoverboard with Mapzen, be sure to use Mapzen's forked library and not the original Hoverboard.

There are also changes in the parent that should be reviewed to determine if they should be pulled back into this fork.

cc @burritojustice @mjcunningham

**Comment by hkrishna** [comment]
There are changes in mapzen's fork that wont make sense for to go into the standard Hoverboard library. So, for now - we should update our documentation/readme.

We could rewrite the hoverboard based demos by creating a new repo, adding the required code for various formats (topojson, geojson, mvt) - this way we wont have to worry about maintaining a fork (keeping the fork in sync with the main library is a pain). 

Thoughts?

**Comment by louh** [comment]
If what you mean is that Mapzen-Hoverboard should extend Hoverboard instead of forking it, :+1:

**Comment by mjcunningham** [comment]
@hkrishna I'll throw something in trello for you. :stuck_out_tongue_winking_eye: :+1: 

I'll close this and track it here: https://github.com/mapzen/hoverboard/issues/7 so we don't forget about it.
